
export const lessonsData = {
    'en': [
        { category: "Letters", keys: "f/j e/i", lesson: "Lesson 1" },
        { category: "Letters", keys: "d/k w/o", lesson: "Lesson 2" },
        { category: "Letters", keys: "s/l q/p", lesson: "Lesson 3" },
        { category: "Letters", keys: "a/; r/u", lesson: "Lesson 4" },
        { category: "Letters", keys: "g/h t/y", lesson: "Lesson 5" },
        { category: "Letters", keys: "v/b n/m", lesson: "Lesson 6" },
        { category: "Letters", keys: "x/c z/`", lesson: "Lesson 7" },
        { category: "Letters", keys: ", . - ", lesson: "Lesson 8" },
        { category: "Words", keys: "Short words", lesson: "Lesson 9" },
        { category: "Words", keys: "Long words", lesson: "Lesson 10" },
        { category: "Words", keys: "Capital short", lesson: "Lesson 11" },
        { category: "Words", keys: "Capital long", lesson: "Lesson 12" },
        { category: "Words", keys: "Short sentences", lesson: "Lesson 13" },
        { category: "Words", keys: "Long sentences", lesson: "Lesson 14" },
        { category: "Numbers", keys: "5-7", lesson: "Lesson 15" },
        { category: "Numbers", keys: "6", lesson: "Lesson 16" },
        { category: "Numbers", keys: "4-8", lesson: "Lesson 17" },
        { category: "Numbers", keys: "3-9", lesson: "Lesson 18" },
        { category: "Numbers", keys: "1-2-0", lesson: "Lesson 19" },
        { category: "Numbers", keys: "All numbers", lesson: "Lesson 20" },
        { category: "Punctuation: Part 1", keys: ", . /", lesson: "Lesson 21" },
        { category: "Punctuation: Part 1", keys: "! +", lesson: "Lesson 22" },
        { category: "Punctuation: Part 1", keys: "< > ?", lesson: "Lesson 23" },
        { category: "Punctuation: Part 1", keys: "; ' \" ", lesson: "Lesson 24" },
        { category: "Punctuation: Part 1", keys: "[ ] - =", lesson: "Lesson 25" },
        { category: "Punctuation: Part 1", keys: "` { }", lesson: "Lesson 26" },
        { category: "Punctuation: Part 2", keys: "( )", lesson: "Lesson 27" },
        { category: "Punctuation: Part 2", keys: ": \" |", lesson: "Lesson 28" },
        { category: "Punctuation: Part 2", keys: "@ _", lesson: "Lesson 29" },
        { category: "Punctuation: Part 2", keys: "# $", lesson: "Lesson 30" },
        { category: "Punctuation: Part 2", keys: "% *", lesson: "Lesson 31" },
        { category: "Punctuation: Part 2", keys: "^ &", lesson: "Lesson 32" }
    ],
    'ru': [
        { category: "Букви", keys: "а/о у/ш", lesson: "Урок 1" },
        { category: "Букви", keys: "в/л ц/щ", lesson: "Урок 2" },
        { category: "Букви", keys: "ы/д й/з", lesson: "Урок 3" },
        { category: "Букви", keys: "м/т е/н", lesson: "Урок 4" },
        { category: "Букви", keys: "к/г с/ь", lesson: "Урок 5" },
        { category: "Букви", keys: "я/ч ф/и", lesson: "Урок 6" },
        { category: "Букви", keys: "х/ъ б/ю", lesson: "Урок 7" },
        { category: "Букви", keys: "ж/э", lesson: "Урок 8" },
        { category: "Слова", keys: "короткі", lesson: "Урок 9" },
        { category: "Слова", keys: "довгі", lesson: "Урок 10" },
        { category: "Слова", keys: "великі короткі", lesson: "Урок 11" },
        { category: "Слова", keys: "великі довгі", lesson: "Урок 12" },
        { category: "Слова", keys: "короткі речення", lesson: "Урок 13" },
        { category: "Слова", keys: "довгі речення", lesson: "Урок 14" },
        { category: "Цифри", keys: "5-7", lesson: "Урок 15" },
        { category: "Цифри", keys: "6", lesson: "Урок 16" },
        { category: "Цифри", keys: "4-8", lesson: "Урок 17" },
        { category: "Цифри", keys: "3-9", lesson: "Урок 18" },
        { category: "Цифри", keys: "1-2-0", lesson: "Урок 19" },
        { category: "Цифри", keys: "усі цифри", lesson: "Урок 20" },
        { category: "Розділові знаки: part 1", keys: ", . /", lesson: "Урок 21" },
        { category: "Розділові знаки: part 1", keys: "! +", lesson: "Урок 22" },
        { category: "Розділові знаки: part 1", keys: "< > ?", lesson: "Урок 23" },
        { category: "Розділові знаки: part 1", keys: "; '' \" ", lesson: "Урок 24" },
        { category: "Розділові знаки: part 1", keys: "[ ] - =", lesson: "Урок 25" },
        { category: "Розділові знаки: part 1", keys: "` { }", lesson: "Урок 26" },
        { category: "Розділові знаки: part 2", keys: "( )", lesson: "Урок 27" },
        { category: "Розділові знаки: part 2", keys: ": \" |", lesson: "Урок 28" },
        { category: "Розділові знаки: part 2", keys: "@ _", lesson: "Урок 29" },
        { category: "Розділові знаки: part 2", keys: "# $", lesson: "Урок 30" },
        { category: "Розділові знаки: part 2", keys: "% *", lesson: "Урок 31" },
        { category: "Розділові знаки: part 2", keys: "^ &", lesson: "Урок 32" }
    ],

    'uk': [
        { category: "Букви", keys: "а/о у/ш", lesson: "Урок 1" },
        { category: "Букви", keys: "в/л ц/щ", lesson: "Урок 2" },
        { category: "Букви", keys: "і/д й/з", lesson: "Урок 3" },
        { category: "Букви", keys: "м/т е/н", lesson: "Урок 4" },
        { category: "Букви", keys: "к/г с/ь", lesson: "Урок 5" },
        { category: "Букви", keys: "я/ч ф/и", lesson: "Урок 6" },
        { category: "Букви", keys: "х/ї б/ю", lesson: "Урок 7" },
        { category: "Букви", keys: "ж/є", lesson: "Урок 8" },
        { category: "Слова", keys: "короткі", lesson: "Урок 9" },
        { category: "Слова", keys: "довгі", lesson: "Урок 10" },
        { category: "Слова", keys: "великі короткі", lesson: "Урок 11" },
        { category: "Слова", keys: "великі довгі", lesson: "Урок 12" },
        { category: "Слова", keys: "короткі речення", lesson: "Урок 13" },
        { category: "Слова", keys: "довгі речення", lesson: "Урок 14" },
        { category: "Цифри", keys: "5-7", lesson: "Урок 15" },
        { category: "Цифри", keys: "6", lesson: "Урок 16" },
        { category: "Цифри", keys: "4-8", lesson: "Урок 17" },
        { category: "Цифри", keys: "3-9", lesson: "Урок 18" },
        { category: "Цифри", keys: "1-2-0", lesson: "Урок 19" },
        { category: "Цифри", keys: "усі цифри", lesson: "Урок 20" },
        { category: "Розділові знаки: part 1", keys: ", . /", lesson: "Урок 21" },
        { category: "Розділові знаки: part 1", keys: "! +", lesson: "Урок 22" },
        { category: "Розділові знаки: part 1", keys: "<> ?", lesson: "Урок 23" },
        { category: "Розділові знаки: part 1", keys: "; '' \\", lesson: "Урок 24" },
        { category: "Розділові знаки: part 1", keys: "[ ] - =", lesson: "Урок 25" },
        { category: "Розділові знаки: part 1", keys: "` { }", lesson: "Урок 26" },
        { category: "Розділові знаки: part 2", keys: "( )", lesson: "Урок 27" },
        { category: "Розділові знаки: part 2", keys: ": \" |", lesson: "Урок 28" },
        { category: "Розділові знаки: part 2", keys: "@ _", lesson: "Урок 29" },
        { category: "Розділові знаки: part 2", keys: "# $", lesson: "Урок 30" },
        { category: "Розділові знаки: part 2", keys: "% *", lesson: "Урок 31" },
        { category: "Розділові знаки: part 2", keys: "^ &", lesson: "Урок 32" }
    ]

};